### ISSUE TITLE
OkHttpAspect我已经写好了，可是运行没有反应

### ISSUE THREAD

**Issue by 1371030** [LiushuiXiaoxia/AndroidHttp#3]
OkHttpAspect我已经写好了，可是运行没有反应，这个要怎么调试？

**Comment by LiushuiXiaoxia** [comment]
具体可以参加下 aspect的插件，我当时写的插件是
```
classpath 'com.android.tools.build:gradle:2.3.0'
```

现在已经很高版本了
```
 classpath 'com.android.tools.build:gradle:3.2.1'
```

会不少的差异。

**Comment by 1371030** [comment]
请问哪能找到OkHttpAspect的示例？

**Comment by LiushuiXiaoxia** [comment]
暂时没有，可借鉴我那个，自己写下，参考地址 https://github.com/HujiangTechnology/gradle_plugin_android_aspectjx
